### ISSUE TITLE
Vunit with Xcelium or Vivado?

### ISSUE THREAD

**Issue by petandpal** [VUnit/vunit#501] opened 2019-05-22 19:35 UTC
Hello, I am trying to run Vunit with Xcelium (using the incisive simulator option) but I am seeing some strange issues. First it cannot find the installation root and is looking for Virtuoso. It then goes forward and gets stuck with vunit_lib not found even though it is specified in the cds.lib file. Any help with this?

setenv VUNIT_SIMULATOR incisive
My path points to <installation dir>/XCELIUM1809/tools/bin

![vunit_incisive_error](https://user-images.githubusercontent.com/50879593/58203040-c9925c00-7c9e-11e9-92ea-2f7d8739b6a8.JPG)

Also are there any plans to have vunit work with Vivado simulator on Linux? Thanks.

**Comment by 1138-4EB** [comment] 2019-05-22 19:46
Ref #325.

**Comment by LarsAsplund** [comment] 2019-05-22 20:21
I've spoken to several users of Cadence simulators interested in VUnit but we cannot provide any good support without simulator licenses and that's why we're asking for help in #325. An alternative is to have Cadence to support the project. I've tried to reach out but no success so far but I know that they've used it internally with Xcelium. I encourage you and any other Cadence user to contact them about the need for official VUnit support. I know of companies considering moving to Cadence but the lack of VUnit support is a concern so Cadence is actually losing business because of this.

**Comment by LarsAsplund** [comment] 2019-05-22 20:21
See #209 for Vivado

**Comment by LarsAsplund** [comment] 2019-05-22 20:31
@petandpal Would you be willing to create a VUnit support request on https://community.cadence.com? Then the rest of us can go there and 👍

**Comment by petandpal** [comment] 2019-05-22 20:33
Sure.

**Comment by LarsAsplund** [comment] 2019-05-22 20:33
@petandpal Please post the link when done

**Comment by petandpal** [comment] 2019-05-22 20:46
https://support.cadence.com/apex/COSCaseDetailPage?CaseID=5000V00001J93GT

**Comment by LarsAsplund** [comment] 2019-05-23 20:20
I can't get access to Cadence support unless I have a license, which I don't. The [user community](https://community.cadence.com) is open though.

**Comment by 1138-4EB** [comment] 2019-09-18 16:13
Closing this as a duplicate of #325 and #209. The support ticket provided above has been copied to #325.

**Closed by 1138-4EB** 2019-09-18 16:13 UTC
Labels: simulator support
